
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_BOOKINGS = 'OBTENER_BOOKINGS';
export const BOOKINGS_ERROR = 'BOOKINGS_ERROR';
export const BOOKINGS_BUSCAR = 'BOOKINGS_BUSCAR';
export const BOOKINGS_BUSCAR_PRECIO = 'BOOKINGS_BUSCAR_PRECIO';



